###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
    "name": "pan",
    "description": "rico",
    "price": "50"
}

###
GET http://localhost:9000/api/products HTTP/1.1

###
GET http://localhost:9000/api/users/63c0da710ed6bc74ea7702ba HTTP/1.1

###
PUT http://localhost:9000/api/users/63c0da710ed6bc74ea7702ba HTTP/1.1
Content-Type: application/json

{
    "name": "petronila",
    "age": "10",
    "email":"gellllllapetro.com"
}

###
DELETE  http://localhost:9000/api/users/63c0da710ed6bc74ea7702ba HTTP/1.1

